[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"

[dependencies.imgui-sys]
version = "0.8.0"

[dependencies]
os = { path = "src/os", package = "os" }
gfx = { path = "src/gfx", package = "gfx" }
win32 = { path = "src/os/win32", package = "win32" }
d3d12 = { path = "src/gfx/d3d12", package = "d3d12" }
