[package]
name = "hotline"
version = "0.1.0"
edition = "2018"

[dependencies.imgui-sys]
version = "0.8.0"

[dependencies]
app = { path = "crates/app", package = "app" }
os = { path = "crates/os", package = "os" }
gfx = { path = "crates/gfx", package = "gfx" }
win32 = { path = "crates/os/win32", package = "win32" }
d3d12 = { path = "crates/gfx/d3d12", package = "d3d12" }
