[package]
name = "gfx"
version = "0.1.0"
edition = "2018"

[lib]
name = "gfx"
path = "gfx.rs"

[dependencies]
os = { path = "../os", package = "os" }
win32 = { path = "../os/win32", package = "win32" }
bitmask = "^0.5.0"